export const SKILLS = {
	ts: 'TypeScript',
	js: 'JavaScript',
	cs: 'C#',
	htmlcss: 'HTML/CSS',
	sql: 'SQL',
	nosql: 'NoSQL',
	python: 'Python',
	node: 'Node',
	react: 'React',
	svelte: 'Svelte',
	aws: 'AWS',
	gcp: 'GCP',
	unity: 'Unity',
	godot: 'Godot',
	canvas: 'Canvas2D',
	webgl: 'WebGL',
	desktop: 'Desktop',
	mobile: 'Mobile',
	consoles: 'Consoles',
	vr: 'VR/AR/XR',
	gamedesign: 'Game Design',
	audio: 'Audio Design',
	vfx: 'VFX Design',
	perf: 'Performance Optimization',
	realtime: 'Realtime Multiplayer',
	webrtc: 'WebRTC',
	diffusion: 'Diffusion Models',
	llm: 'LLM Models',
} as const;

export const TAGS = {
	subtle: 'Subtlety',
	general: 'General',
	pro: 'Professional',
	extra: 'Extracurricular',
	web: 'Web Dev',
	games: 'Game Dev',
	ai: 'AI Dev',
	design: 'Design',
	lead: 'Leadership',
	onlyi: 'Only I Could Solve',
	process: 'Process',
	docs: 'Documentation',
} as const;

export const TAG_SUBTLE: keyof typeof TAGS = 'subtle';
